### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by Peterr-K** [synzen/MonitoRSS#200]
Hi

after today's update of the clone repository bot can't start:

```
root@Lucy /home/user/MonitoRSS-Clone # /usr/bin/node /home/user/MonitoRSS-Clone/bot-web.js
/home/user/MonitoRSS-Clone/node_modules/monitorss/src/structs/Guild.js:39
    maxGuilds = Math.max(maxGuilds, data?.maxFeeds)
                                         ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/MonitoRSS-Clone/node_modules/monitorss/src/structs/db/Feed.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/MonitoRSS-Clone/node_modules/monitorss/src/initialization/setupRateLimiters.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
```

**Comment by synzen** [comment]
Thanks for the report, it should be fixed now (for issues related to the clone, please open in issue in the clone repo). You may try again

**Comment by Peterr-K** [comment]
fixed, thank you.
