### ISSUE TITLE
Warning: Feed parsing took too long

### ISSUE THREAD

**Issue by jrmgx** [synzen/MonitoRSS#226]
## Describe the bug

With this feed: https://www.investegate.co.uk/Rss.aspx?company=agl
and similar (https://www.investegate.co.uk/Rss.aspx?company=uog ...), 
I get a warning:

```log
[2021-08-19 15:29:24.607 +0000] WARN    : [default] Skipping https://www.investegate.co.uk/Rss.aspx?company=agl
    error: {
      "type": "FeedParserError",
      "message": "Feed parsing took too long",                                                
      "stack":
          Error: Feed parsing took too long
              at Timeout._onTimeout (/app/node_modules/monitorss/src/util/FeedFetcher.js:198:16)
              at listOnTimeout (internal/timers.js:554:17)                                    
              at processTimers (internal/timers.js:497:7)                                     
    }                 
```

and nothing get posted by the bot (which seem ledgit regarding the error)

## To Reproduce

1. Add this feed https://www.investegate.co.uk/Rss.aspx?company=uog
2. Wait for it to be fetched 
3. See error in log

## Expected behavior

I understand that the code has some safeguard, but from what I read here
https://github.com/synzen/MonitoRSS/blob/1173c4c1c47685b0896d27e37d0839dced580631/src/util/FeedFetcher.js#L198 
it's only 10 seconds (probably a bit low for the feed in my example) 
and it's not accessible in config (where I could change it for my needs)

So my question are,
- Did I understand the problem right?
- Could the *parse timeout* be an option I could change?

## Branch (please specify one):

master

## Additional context

Thank you for your time! This project helps a lot :)

**Comment by jrmgx** [comment]
https://github.com/synzen/MonitoRSS/commit/ec1d978d2c0ad0016e527022c7fd7f1ee3dd9861 closes this issue, thank you
