### ISSUE TITLE
Schedule run failure

### ISSUE THREAD

**Issue by thespad** [synzen/MonitoRSS#321]
## Describe the bug

On schedule run the bot crashes with
```
 [2023-02-01 11:33:10.733 +0000] ERROR       : [M] Error during schedule run
     TypeError: randomUUID is not a function
         at ScheduleRun.processBatch (/app/node_modules/monitorss/src/structs/ScheduleRun.js:521:19)
         at internal/util.js:297:30
         at new Promise (<anonymous>)
         at ScheduleRun.processBatch (internal/util.js:296:12)
         at ScheduleRun.run (/app/node_modules/monitorss/src/structs/ScheduleRun.js:437:23)
         at processTicksAndRejections (internal/process/task_queues.js:97:5)
         at async ScheduleManager.run (/app/node_modules/monitorss/src/structs/ScheduleManager.js:291:7)
```

It seems to be related to this commit https://github.com/synzen/MonitoRSS/commit/0635fcaa9fbe1c93aa4cbecbf11851695f0b2e4e

## To Reproduce

Error occurs when any new or existing feed schedule runs

## Expected behavior

Schedule should run successfully

## Screenshots

N/A

## Branch (please specify one):

Master

**Comment by synzen** [comment]
Thanks for the report, this should be fixed in the latest version now.
